// Comprehensive Global Cities & Telemetry Landmarks Dataset
// Provides crisp vector markers & labels for countries, states, and regional metropolitan centers

export const WORLD_CITIES = [
  // --- North America ---
  { name: 'New York', country: 'United States', state: 'New York', lat: 40.7128, lng: -74.006, isCapital: false, isMegacity: true },
  { name: 'Washington D.C.', country: 'United States', state: 'District of Columbia', lat: 38.9072, lng: -77.0369, isCapital: true },
  { name: 'Los Angeles', country: 'United States', state: 'California', lat: 34.0522, lng: -118.2437, isCapital: false, isMegacity: true },
  { name: 'San Francisco', country: 'United States', state: 'California', lat: 37.7749, lng: -122.4194, isCapital: false },
  { name: 'Seattle', country: 'United States', state: 'Washington', lat: 47.6062, lng: -122.3321, isCapital: false },
  { name: 'Chicago', country: 'United States', state: 'Illinois', lat: 41.8781, lng: -87.6298, isCapital: false, isMegacity: true },
  { name: 'Austin', country: 'United States', state: 'Texas', lat: 30.2672, lng: -97.7431, isCapital: false },
  { name: 'Houston', country: 'United States', state: 'Texas', lat: 29.7604, lng: -95.3698, isCapital: false },
  { name: 'Miami', country: 'United States', state: 'Florida', lat: 25.7617, lng: -80.1918, isCapital: false },
  { name: 'Atlanta', country: 'United States', state: 'Georgia', lat: 33.749, lng: -84.388, isCapital: false },
  { name: 'Boston', country: 'United States', state: 'Massachusetts', lat: 42.3601, lng: -71.0589, isCapital: false },
  { name: 'Toronto', country: 'Canada', state: 'Ontario', lat: 43.6532, lng: -79.3832, isCapital: false, isMegacity: true },
  { name: 'Ottawa', country: 'Canada', state: 'Ontario', lat: 45.4215, lng: -75.6972, isCapital: true },
  { name: 'Vancouver', country: 'Canada', state: 'British Columbia', lat: 49.2827, lng: -123.1207, isCapital: false },
  { name: 'Montreal', country: 'Canada', state: 'Quebec', lat: 45.5017, lng: -73.5673, isCapital: false },
  { name: 'Mexico City', country: 'Mexico', state: 'CDMX', lat: 19.4326, lng: -99.1332, isCapital: true, isMegacity: true },

  // --- Europe ---
  { name: 'London', country: 'United Kingdom', state: 'England', lat: 51.5074, lng: -0.1278, isCapital: true, isMegacity: true },
  { name: 'Paris', country: 'France', state: 'Île-de-France', lat: 48.8566, lng: 2.3522, isCapital: true, isMegacity: true },
  { name: 'Berlin', country: 'Germany', state: 'Berlin', lat: 52.52, lng: 13.405, isCapital: true },
  { name: 'Munich', country: 'Germany', state: 'Bavaria', lat: 48.1351, lng: 11.582, isCapital: false },
  { name: 'Frankfurt', country: 'Germany', state: 'Hesse', lat: 50.1109, lng: 8.6821, isCapital: false },
  { name: 'Amsterdam', country: 'Netherlands', state: 'North Holland', lat: 52.3676, lng: 4.9041, isCapital: true },
  { name: 'Brussels', country: 'Belgium', state: 'Brussels', lat: 50.8503, lng: 4.3517, isCapital: true },
  { name: 'Zurich', country: 'Switzerland', state: 'Zurich', lat: 47.3769, lng: 8.5417, isCapital: false },
  { name: 'Geneva', country: 'Switzerland', state: 'Geneva', lat: 46.2044, lng: 6.1432, isCapital: false },
  { name: 'Vienna', country: 'Austria', state: 'Vienna', lat: 48.2082, lng: 16.3738, isCapital: true },
  { name: 'Madrid', country: 'Spain', state: 'Community of Madrid', lat: 40.4168, lng: -3.7038, isCapital: true },
  { name: 'Barcelona', country: 'Spain', state: 'Catalonia', lat: 41.3851, lng: 2.1734, isCapital: false },
  { name: 'Rome', country: 'Italy', state: 'Lazio', lat: 41.9028, lng: 12.4964, isCapital: true },
  { name: 'Milan', country: 'Italy', state: 'Lombardy', lat: 45.4642, lng: 9.19, isCapital: false },
  { name: 'Stockholm', country: 'Sweden', state: 'Stockholm', lat: 59.3293, lng: 18.0686, isCapital: true },
  { name: 'Oslo', country: 'Norway', state: 'Oslo', lat: 59.9139, lng: 10.7522, isCapital: true },
  { name: 'Helsinki', country: 'Finland', state: 'Uusimaa', lat: 60.1699, lng: 24.9384, isCapital: true },
  { name: 'Copenhagen', country: 'Denmark', state: 'Hovedstaden', lat: 55.6761, lng: 12.5683, isCapital: true },
  { name: 'Dublin', country: 'Ireland', state: 'Leinster', lat: 53.3498, lng: -6.2603, isCapital: true },
  { name: 'Warsaw', country: 'Poland', state: 'Masovia', lat: 52.2297, lng: 21.0122, isCapital: true },
  { name: 'Prague', country: 'Czechia', state: 'Prague', lat: 50.0755, lng: 14.4378, isCapital: true },
  { name: 'Athens', country: 'Greece', state: 'Attica', lat: 37.9838, lng: 23.7275, isCapital: true },
  { name: 'Lisbon', country: 'Portugal', state: 'Lisbon', lat: 38.7223, lng: -9.1393, isCapital: true },
  { name: 'Kyiv', country: 'Ukraine', state: 'Kyiv', lat: 50.4501, lng: 30.5234, isCapital: true },
  { name: 'Moscow', country: 'Russia', state: 'Moscow', lat: 55.7558, lng: 37.6173, isCapital: true, isMegacity: true },

  // --- Asia & Middle East ---
  { name: 'Tokyo', country: 'Japan', state: 'Tokyo', lat: 35.6762, lng: 139.6503, isCapital: true, isMegacity: true },
  { name: 'Osaka', country: 'Japan', state: 'Kansai', lat: 34.6937, lng: 135.5023, isCapital: false },
  { name: 'Seoul', country: 'South Korea', state: 'Seoul', lat: 37.5665, lng: 126.978, isCapital: true, isMegacity: true },
  { name: 'Beijing', country: 'China', state: 'Beijing', lat: 39.9042, lng: 116.4074, isCapital: true, isMegacity: true },
  { name: 'Shanghai', country: 'China', state: 'Shanghai', lat: 31.2304, lng: 121.4737, isCapital: false, isMegacity: true },
  { name: 'Shenzhen', country: 'China', state: 'Guangdong', lat: 22.5431, lng: 114.0579, isCapital: false },
  { name: 'Hong Kong', country: 'Hong Kong', state: 'HK', lat: 22.3193, lng: 114.1694, isCapital: false, isMegacity: true },
  { name: 'Taipei', country: 'Taiwan', state: 'Taipei', lat: 25.033, lng: 121.5654, isCapital: true },
  { name: 'Singapore', country: 'Singapore', state: 'Singapore', lat: 1.3521, lng: 103.8198, isCapital: true },
  { name: 'Bangkok', country: 'Thailand', state: 'Bangkok', lat: 13.7563, lng: 100.5018, isCapital: true, isMegacity: true },
  { name: 'Kuala Lumpur', country: 'Malaysia', state: 'Federal Territory', lat: 3.139, lng: 101.6869, isCapital: true },
  { name: 'Jakarta', country: 'Indonesia', state: 'Jakarta', lat: -6.2088, lng: 106.8456, isCapital: true, isMegacity: true },
  { name: 'Manila', country: 'Philippines', state: 'Metro Manila', lat: 14.5995, lng: 120.9842, isCapital: true },
  { name: 'Hanoi', country: 'Vietnam', state: 'Hanoi', lat: 21.0285, lng: 105.8542, isCapital: true },
  { name: 'Ho Chi Minh City', country: 'Vietnam', state: 'South', lat: 10.8231, lng: 106.6297, isCapital: false },
  { name: 'New Delhi', country: 'India', state: 'Delhi', lat: 28.6139, lng: 77.209, isCapital: true, isMegacity: true },
  { name: 'Mumbai', country: 'India', state: 'Maharashtra', lat: 19.076, lng: 72.8777, isCapital: false, isMegacity: true },
  { name: 'Bengaluru', country: 'India', state: 'Karnataka', lat: 12.9716, lng: 77.5946, isCapital: false, isMegacity: true },
  { name: 'Hyderabad', country: 'India', state: 'Telangana', lat: 17.385, lng: 78.4867, isCapital: false },
  { name: 'Chennai', country: 'India', state: 'Tamil Nadu', lat: 13.0827, lng: 80.2707, isCapital: false },
  { name: 'Kolkata', country: 'India', state: 'West Bengal', lat: 22.5726, lng: 88.3639, isCapital: false },
  { name: 'Dubai', country: 'United Arab Emirates', state: 'Dubai', lat: 25.2048, lng: 55.2708, isCapital: false, isMegacity: true },
  { name: 'Abu Dhabi', country: 'United Arab Emirates', state: 'Abu Dhabi', lat: 24.4539, lng: 54.3773, isCapital: true },
  { name: 'Riyadh', country: 'Saudi Arabia', state: 'Riyadh', lat: 24.7136, lng: 46.6753, isCapital: true },
  { name: 'Doha', country: 'Qatar', state: 'Doha', lat: 25.2854, lng: 51.531, isCapital: true },
  { name: 'Tel Aviv', country: 'Israel', state: 'Tel Aviv', lat: 32.0853, lng: 34.7818, isCapital: false },
  { name: 'Istanbul', country: 'Turkey', state: 'Marmara', lat: 41.0082, lng: 28.9784, isCapital: false, isMegacity: true },
  { name: 'Ankara', country: 'Turkey', state: 'Central Anatolia', lat: 39.9334, lng: 32.8597, isCapital: true },

  // --- Oceania ---
  { name: 'Sydney', country: 'Australia', state: 'New South Wales', lat: -33.8688, lng: 151.2093, isCapital: false, isMegacity: true },
  { name: 'Melbourne', country: 'Australia', state: 'Victoria', lat: -37.8136, lng: 144.9631, isCapital: false },
  { name: 'Brisbane', country: 'Australia', state: 'Queensland', lat: -27.4698, lng: 153.0251, isCapital: false },
  { name: 'Perth', country: 'Australia', state: 'Western Australia', lat: -31.9505, lng: 115.8605, isCapital: false },
  { name: 'Canberra', country: 'Australia', state: 'Australian Capital Territory', lat: -35.2809, lng: 149.13, isCapital: true },
  { name: 'Auckland', country: 'New Zealand', state: 'North Island', lat: -36.8485, lng: 174.7633, isCapital: false },
  { name: 'Wellington', country: 'New Zealand', state: 'North Island', lat: -41.2865, lng: 174.7762, isCapital: true },

  // --- South America ---
  { name: 'São Paulo', country: 'Brazil', state: 'São Paulo', lat: -23.5505, lng: -46.6333, isCapital: false, isMegacity: true },
  { name: 'Rio de Janeiro', country: 'Brazil', state: 'Rio de Janeiro', lat: -22.9068, lng: -43.1729, isCapital: false },
  { name: 'Brasília', country: 'Brazil', state: 'Federal District', lat: -15.7975, lng: -47.8919, isCapital: true },
  { name: 'Buenos Aires', country: 'Argentina', state: 'Capital Federal', lat: -34.6037, lng: -58.3816, isCapital: true, isMegacity: true },
  { name: 'Santiago', country: 'Chile', state: 'Santiago Metropolitan', lat: -33.4489, lng: -70.6693, isCapital: true },
  { name: 'Bogota', country: 'Colombia', state: 'Cundinamarca', lat: 4.711, lng: -74.0721, isCapital: true },
  { name: 'Lima', country: 'Peru', state: 'Lima Province', lat: -12.0464, lng: -77.0428, isCapital: true },

  // --- Africa ---
  { name: 'Cairo', country: 'Egypt', state: 'Cairo', lat: 30.0444, lng: 31.2357, isCapital: true, isMegacity: true },
  { name: 'Johannesburg', country: 'South Africa', state: 'Gauteng', lat: -26.2041, lng: 28.0473, isCapital: false, isMegacity: true },
  { name: 'Cape Town', country: 'South Africa', state: 'Western Cape', lat: -33.9249, lng: 18.4241, isCapital: true },
  { name: 'Nairobi', country: 'Kenya', state: 'Nairobi', lat: -1.2921, lng: 36.8219, isCapital: true },
  { name: 'Lagos', country: 'Nigeria', state: 'Lagos', lat: 6.5244, lng: 3.3792, isCapital: false, isMegacity: true },
  { name: 'Casablanca', country: 'Morocco', state: 'Casablanca-Settat', lat: 33.5731, lng: -7.5898, isCapital: false },
  { name: 'Addis Ababa', country: 'Ethiopia', state: 'Addis Ababa', lat: 9.03, lng: 38.74, isCapital: true }
];
