/**
 * Free Autonomous Tools for James AI Community Agent
 * All tools are 100% free and require zero paid API keys.
 */

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

class FreeToolsService {
  constructor(uploadsDir) {
    this.uploadsDir = uploadsDir || path.join(__dirname, '..', 'uploads');
    if (!fs.existsSync(this.uploadsDir)) {
      fs.mkdirSync(this.uploadsDir, { recursive: true });
    }
  }

  /**
   * 1. Free AI Image Generation via Pollinations.ai (100% Free, No API Key)
   */
  async generateImage(prompt, options = {}) {
    if (!prompt || typeof prompt !== 'string') {
      throw new Error('Image prompt is required');
    }

    const cleanPrompt = prompt.trim();
    const seed = Math.floor(Math.random() * 1000000);
    const width = options.width || 1024;
    const height = options.height || 1024;
    const pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(cleanPrompt)}?width=${width}&height=${height}&seed=${seed}&nologo=true`;

    try {
      console.log(`[FreeTools]: Generating image via Pollinations with prompt: "${cleanPrompt}"`);
      const res = await fetch(pollinationsUrl, {
        signal: AbortSignal.timeout(30000)
      });

      if (!res.ok) {
        throw new Error(`Pollinations HTTP ${res.status}`);
      }

      const buffer = Buffer.from(await res.arrayBuffer());
      const filename = `james_art_${Date.now()}_${Math.random().toString(36).substring(2, 7)}.png`;
      const filePath = path.join(this.uploadsDir, filename);

      await fs.promises.writeFile(filePath, buffer);
      console.log(`[FreeTools]: Image saved successfully to ${filename}`);

      return {
        success: true,
        filename,
        imageUrl: `/uploads/${filename}`,
        prompt: cleanPrompt
      };
    } catch (err) {
      console.error('[FreeTools]: Image generation failed:', err.message);
      return {
        success: false,
        error: err.message,
        prompt: cleanPrompt
      };
    }
  }

  /**
   * 2. Free PDF Document Creator using PDFKit (100% Local, No API Key)
   */
  async generatePdf(title, content, requestedFilename) {
    return new Promise((resolve, reject) => {
      try {
        const safeTitle = (title || 'Document').replace(/[^\w\s-]/g, '').trim();
        const baseName = (requestedFilename || safeTitle || 'document')
          .replace(/[^\w-]/g, '_')
          .toLowerCase();
        const filename = `${baseName}_${Date.now()}.pdf`;
        const filePath = path.join(this.uploadsDir, filename);

        const doc = new PDFDocument({
          margin: 40,
          size: 'A4'
        });

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Header Background Banner
        doc.rect(0, 0, doc.page.width, 70).fill('#0f172a');

        // Header Title
        doc.fillColor('#00f3ff')
          .fontSize(20)
          .font('Helvetica-Bold')
          .text(title || 'ShadowTalk Document', 40, 20, { width: doc.page.width - 80 });

        doc.fillColor('#94a3b8')
          .fontSize(9)
          .font('Helvetica')
          .text(`Generated by James AI on ${new Date().toUTCString()}`, 40, 48);

        doc.moveDown(3);
        doc.fillColor('#1e293b');

        // Document Body
        const lines = (content || '').split('\n');
        for (const line of lines) {
          const trimmed = line.trim();
          if (trimmed.startsWith('# ')) {
            doc.moveDown(0.8)
              .fillColor('#0f172a')
              .fontSize(16)
              .font('Helvetica-Bold')
              .text(trimmed.replace(/^#\s*/, ''));
            doc.moveDown(0.3);
          } else if (trimmed.startsWith('## ')) {
            doc.moveDown(0.6)
              .fillColor('#0f172a')
              .fontSize(13)
              .font('Helvetica-Bold')
              .text(trimmed.replace(/^##\s*/, ''));
            doc.moveDown(0.2);
          } else if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
            // Markdown Table Row
            doc.fontSize(9)
              .font('Helvetica')
              .fillColor('#334155')
              .text(trimmed, { indent: 10 });
          } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
            doc.fontSize(10)
              .font('Helvetica')
              .fillColor('#334155')
              .text(`• ${trimmed.slice(2)}`, { indent: 15 });
          } else if (trimmed.length > 0) {
            doc.fontSize(10)
              .font('Helvetica')
              .fillColor('#1e293b')
              .text(trimmed, { lineGap: 3 });
          } else {
            doc.moveDown(0.4);
          }
        }

        // Footer
        doc.fontSize(8)
          .fillColor('#94a3b8')
          .text(
            'ShadowTalk Community Platform — Verified Document Attachment',
            40,
            doc.page.height - 35,
            { align: 'center', width: doc.page.width - 80 }
          );

        doc.end();

        stream.on('finish', () => {
          const stats = fs.statSync(filePath);
          console.log(`[FreeTools]: PDF generated successfully: ${filename} (${stats.size} bytes)`);
          resolve({
            success: true,
            filename,
            fileUrl: `/uploads/${filename}`,
            fileSize: stats.size,
            title: title || 'Document'
          });
        });

        stream.on('error', (err) => reject(err));
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * 3. Free Math & Calculator Evaluator (100% Free, Safe)
   */
  calculate(expression) {
    if (!expression || typeof expression !== 'string') {
      return { success: false, error: 'Empty expression' };
    }

    try {
      let expr = expression
        .replace(/\bsqrt\b/gi, 'Math.sqrt')
        .replace(/\bsin\b/gi, 'Math.sin')
        .replace(/\bcos\b/gi, 'Math.cos')
        .replace(/\btan\b/gi, 'Math.tan')
        .replace(/\babs\b/gi, 'Math.abs')
        .replace(/\bround\b/gi, 'Math.round')
        .replace(/\bfloor\b/gi, 'Math.floor')
        .replace(/\bceil\b/gi, 'Math.ceil')
        .replace(/\bpow\b/gi, 'Math.pow')
        .replace(/\blog\b/gi, 'Math.log')
        .replace(/\bpi\b/gi, 'Math.PI')
        .replace(/\^/g, '**');

      // Ensure expression only contains safe mathematical characters
      if (!/^[0-9+\-*/().%*,\sMath.sqrtaincoelwbEPI]+$/.test(expr)) {
        return { success: false, error: 'Invalid characters in expression' };
      }

      const compute = new Function(`"use strict"; return (${expr});`);
      const result = compute();

      if (typeof result !== 'number' || isNaN(result)) {
        return { success: false, error: 'Could not evaluate mathematical expression' };
      }

      return {
        success: true,
        expression,
        result: Number(result.toFixed(6))
      };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }

  /**
   * 4. Free Weather API via Open-Meteo (100% Free, No Key)
   */
  async getWeather(location) {
    if (!location) return { success: false, error: 'Location required' };
    try {
      // 1. Geocode location to lat/lon via Open-Meteo free geocoding
      const geoRes = await fetch(
        `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(location)}&count=1&language=en&format=json`,
        { signal: AbortSignal.timeout(6000) }
      );
      const geoData = await geoRes.json();
      const place = geoData.results?.[0];
      if (!place) {
        return { success: false, error: `Could not find coordinates for "${location}"` };
      }

      // 2. Fetch current weather
      const weatherRes = await fetch(
        `https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m&timezone=auto`,
        { signal: AbortSignal.timeout(6000) }
      );
      const weatherData = await weatherRes.json();
      const current = weatherData.current;

      return {
        success: true,
        location: `${place.name}, ${place.country || ''}`,
        temperature: `${current.temperature_2m}°C`,
        humidity: `${current.relative_humidity_2m}%`,
        windSpeed: `${current.wind_speed_10m} km/h`
      };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }

  /**
   * 5. Free QR Code Generator via public free API
   */
  async generateQrCode(text) {
    if (!text) return { success: false, error: 'Text required' };
    try {
      const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(text)}`;
      const res = await fetch(qrUrl, { signal: AbortSignal.timeout(10000) });
      if (!res.ok) throw new Error(`QR API HTTP ${res.status}`);

      const buffer = Buffer.from(await res.arrayBuffer());
      const filename = `qr_${Date.now()}.png`;
      const filePath = path.join(this.uploadsDir, filename);
      await fs.promises.writeFile(filePath, buffer);

      return {
        success: true,
        filename,
        imageUrl: `/uploads/${filename}`,
        text
      };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }
}

module.exports = { FreeToolsService };
